/*
 * This file is generated by jOOQ.
 */
package cn.vertxup.integration.domain.tables;


import cn.vertxup.integration.domain.Db;
import cn.vertxup.integration.domain.Keys;
import cn.vertxup.integration.domain.tables.records.DResultRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DResult extends TableImpl<DResultRecord> {

    /**
     * The reference instance of <code>DB_ETERNAL.D_RESULT</code>
     */
    public static final DResult D_RESULT = new DResult();
    private static final long serialVersionUID = 1L;
    /**
     * The column <code>DB_ETERNAL.D_RESULT.KEY</code>. 「key」- 评价主键
     */
    public final TableField<DResultRecord, String> KEY = createField(DSL.name("KEY"), SQLDataType.VARCHAR(36).nullable(false), this, "「key」- 评价主键");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.CODE</code>. 「code」- 评价编号
     */
    public final TableField<DResultRecord, String> CODE = createField(DSL.name("CODE"), SQLDataType.VARCHAR(255), this, "「code」- 评价编号");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.NAME</code>. 「name」- 评价标题
     */
    public final TableField<DResultRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(255), this, "「name」- 评价标题");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.TYPE</code>. 「type」- 评价类型
     */
    public final TableField<DResultRecord, String> TYPE = createField(DSL.name("TYPE"), SQLDataType.VARCHAR(128), this, "「type」- 评价类型");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.SORT</code>. 「sort」- 评价排序
     */
    public final TableField<DResultRecord, Integer> SORT = createField(DSL.name("SORT"), SQLDataType.INTEGER, this, "「sort」- 评价排序");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.CONTENT</code>. 「content」- 备注内容、评价内容
     */
    public final TableField<DResultRecord, String> CONTENT = createField(DSL.name("CONTENT"), SQLDataType.CLOB, this, "「content」- 备注内容、评价内容");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.SCORE</code>. 「score」- 分数
     */
    public final TableField<DResultRecord, BigDecimal> SCORE = createField(DSL.name("SCORE"), SQLDataType.DECIMAL(18, 4), this, "「score」- 分数");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.SCORE_MARK</code>. 「scoreMark」-
     * 评价对应文字描述，符号
     */
    public final TableField<DResultRecord, String> SCORE_MARK = createField(DSL.name("SCORE_MARK"), SQLDataType.VARCHAR(128), this, "「scoreMark」- 评价对应文字描述，符号");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.SCORE_GRADE</code>. 「scoreGrade」-
     * 等级信息，数值越大等级越高
     */
    public final TableField<DResultRecord, Integer> SCORE_GRADE = createField(DSL.name("SCORE_GRADE"), SQLDataType.INTEGER, this, "「scoreGrade」- 等级信息，数值越大等级越高");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.MODEL_ID</code>. 「modelId」-
     * 关联的模型identifier，用于描述
     */
    public final TableField<DResultRecord, String> MODEL_ID = createField(DSL.name("MODEL_ID"), SQLDataType.VARCHAR(255), this, "「modelId」- 关联的模型identifier，用于描述");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.MODEL_KEY</code>. 「modelKey」-
     * 关联的模型记录ID，用于描述哪一个Model中的记录
     */
    public final TableField<DResultRecord, String> MODEL_KEY = createField(DSL.name("MODEL_KEY"), SQLDataType.VARCHAR(36), this, "「modelKey」- 关联的模型记录ID，用于描述哪一个Model中的记录");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.MADE_NAME</code>. 「madeName」- 评价人姓名
     */
    public final TableField<DResultRecord, String> MADE_NAME = createField(DSL.name("MADE_NAME"), SQLDataType.VARCHAR(123), this, "「madeName」- 评价人姓名");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.MADE_AT</code>. 「madeAt」- 评价时间
     */
    public final TableField<DResultRecord, LocalDateTime> MADE_AT = createField(DSL.name("MADE_AT"), SQLDataType.LOCALDATETIME(0), this, "「madeAt」- 评价时间");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.SIGMA</code>. 「sigma」- 统一标识
     */
    public final TableField<DResultRecord, String> SIGMA = createField(DSL.name("SIGMA"), SQLDataType.VARCHAR(32), this, "「sigma」- 统一标识");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.LANGUAGE</code>. 「language」- 使用的语言
     */
    public final TableField<DResultRecord, String> LANGUAGE = createField(DSL.name("LANGUAGE"), SQLDataType.VARCHAR(10), this, "「language」- 使用的语言");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.ACTIVE</code>. 「active」- 是否启用
     */
    public final TableField<DResultRecord, Boolean> ACTIVE = createField(DSL.name("ACTIVE"), SQLDataType.BIT, this, "「active」- 是否启用");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.METADATA</code>. 「metadata」- 附加配置数据
     */
    public final TableField<DResultRecord, String> METADATA = createField(DSL.name("METADATA"), SQLDataType.CLOB, this, "「metadata」- 附加配置数据");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    public final TableField<DResultRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(0), this, "「createdAt」- 创建时间");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.CREATED_BY</code>. 「createdBy」- 创建人
     */
    public final TableField<DResultRecord, String> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.VARCHAR(36), this, "「createdBy」- 创建人");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    public final TableField<DResultRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(0), this, "「updatedAt」- 更新时间");
    /**
     * The column <code>DB_ETERNAL.D_RESULT.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    public final TableField<DResultRecord, String> UPDATED_BY = createField(DSL.name("UPDATED_BY"), SQLDataType.VARCHAR(36), this, "「updatedBy」- 更新人");

    private DResult(Name alias, Table<DResultRecord> aliased) {
        this(alias, aliased, null);
    }

    private DResult(Name alias, Table<DResultRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>DB_ETERNAL.D_RESULT</code> table reference
     */
    public DResult(String alias) {
        this(DSL.name(alias), D_RESULT);
    }

    /**
     * Create an aliased <code>DB_ETERNAL.D_RESULT</code> table reference
     */
    public DResult(Name alias) {
        this(alias, D_RESULT);
    }

    /**
     * Create a <code>DB_ETERNAL.D_RESULT</code> table reference
     */
    public DResult() {
        this(DSL.name("D_RESULT"), null);
    }

    public <O extends Record> DResult(Table<O> child, ForeignKey<O, DResultRecord> key) {
        super(child, key, D_RESULT);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DResultRecord> getRecordType() {
        return DResultRecord.class;
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Db.DB_ETERNAL;
    }

    @Override
    public UniqueKey<DResultRecord> getPrimaryKey() {
        return Keys.KEY_D_RESULT_PRIMARY;
    }

    @Override
    public DResult as(String alias) {
        return new DResult(DSL.name(alias), this);
    }

    @Override
    public DResult as(Name alias) {
        return new DResult(alias, this);
    }

    @Override
    public DResult as(Table<?> alias) {
        return new DResult(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DResult rename(String name) {
        return new DResult(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DResult rename(Name name) {
        return new DResult(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DResult rename(Table<?> name) {
        return new DResult(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row21 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row21<String, String, String, String, Integer, String, BigDecimal, String, Integer, String, String, String, LocalDateTime, String, String, Boolean, String, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function21<? super String, ? super String, ? super String, ? super String, ? super Integer, ? super String, ? super BigDecimal, ? super String, ? super Integer, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super String, ? super String, ? super Boolean, ? super String, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function21<? super String, ? super String, ? super String, ? super String, ? super Integer, ? super String, ? super BigDecimal, ? super String, ? super Integer, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super String, ? super String, ? super Boolean, ? super String, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
