/*
 * This file is generated by jOOQ.
 */
package cn.vertxup.doc.domain.tables;


import cn.vertxup.doc.domain.Keys;
import cn.vertxup.doc.domain.Zdb;
import cn.vertxup.doc.domain.tables.records.DQanswerRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function11;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DQanswer extends TableImpl<DQanswerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ZDB.D_QANSWER</code>
     */
    public static final DQanswer D_QANSWER = new DQanswer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DQanswerRecord> getRecordType() {
        return DQanswerRecord.class;
    }

    /**
     * The column <code>ZDB.D_QANSWER.REF_ID</code>. 「refId」- 关联考卷中问题实例，对应
     * D_PAPER_REF 表中内容
     */
    public final TableField<DQanswerRecord, String> REF_ID = createField(DSL.name("REF_ID"), SQLDataType.VARCHAR(36).nullable(false), this, "「refId」- 关联考卷中问题实例，对应 D_PAPER_REF 表中内容");

    /**
     * The column <code>ZDB.D_QANSWER.ANSWER_ID</code>. 「answerId」- 考卷ID
     */
    public final TableField<DQanswerRecord, String> ANSWER_ID = createField(DSL.name("ANSWER_ID"), SQLDataType.VARCHAR(36), this, "「answerId」- 考卷ID");

    /**
     * The column <code>ZDB.D_QANSWER.PAPER_ID</code>. 「paperId」- 规则所属考卷ID
     */
    public final TableField<DQanswerRecord, String> PAPER_ID = createField(DSL.name("PAPER_ID"), SQLDataType.VARCHAR(36), this, "「paperId」- 规则所属考卷ID");

    /**
     * The column <code>ZDB.D_QANSWER.TYPE</code>. 「type」- 规则类型
     */
    public final TableField<DQanswerRecord, String> TYPE = createField(DSL.name("TYPE"), SQLDataType.VARCHAR(128).nullable(false), this, "「type」- 规则类型");

    /**
     * The column <code>ZDB.D_QANSWER.QUESTION_ID</code>. 「questionId」- 问题ID
     */
    public final TableField<DQanswerRecord, String> QUESTION_ID = createField(DSL.name("QUESTION_ID"), SQLDataType.VARCHAR(36), this, "「questionId」- 问题ID");

    /**
     * The column <code>ZDB.D_QANSWER.IS_REQUIRED</code>. 「isRequired」- 必答题
     */
    public final TableField<DQanswerRecord, Boolean> IS_REQUIRED = createField(DSL.name("IS_REQUIRED"), SQLDataType.BIT, this, "「isRequired」- 必答题");

    /**
     * The column <code>ZDB.D_QANSWER.IS_ATTACHED</code>. 「isAttached」- 附件必须
     */
    public final TableField<DQanswerRecord, Boolean> IS_ATTACHED = createField(DSL.name("IS_ATTACHED"), SQLDataType.BIT, this, "「isAttached」- 附件必须");

    /**
     * The column <code>ZDB.D_QANSWER.IS_PROOF</code>. 「isProof」- 证据必须
     */
    public final TableField<DQanswerRecord, Boolean> IS_PROOF = createField(DSL.name("IS_PROOF"), SQLDataType.BIT, this, "「isProof」- 证据必须");

    /**
     * The column <code>ZDB.D_QANSWER.RULE_SET</code>. 「ruleSet」- 规则分批执行
     */
    public final TableField<DQanswerRecord, String> RULE_SET = createField(DSL.name("RULE_SET"), SQLDataType.VARCHAR(255).nullable(false), this, "「ruleSet」- 规则分批执行");

    /**
     * The column <code>ZDB.D_QANSWER.RULE_CONFIG</code>. 「ruleConfig」- 规则相关配置
     */
    public final TableField<DQanswerRecord, String> RULE_CONFIG = createField(DSL.name("RULE_CONFIG"), SQLDataType.CLOB, this, "「ruleConfig」- 规则相关配置");

    /**
     * The column <code>ZDB.D_QANSWER.RULE_COMPONENT</code>. 「ruleComponent」-
     * 规则执行组件（扩展用）
     */
    public final TableField<DQanswerRecord, String> RULE_COMPONENT = createField(DSL.name("RULE_COMPONENT"), SQLDataType.VARCHAR(255), this, "「ruleComponent」- 规则执行组件（扩展用）");

    private DQanswer(Name alias, Table<DQanswerRecord> aliased) {
        this(alias, aliased, null);
    }

    private DQanswer(Name alias, Table<DQanswerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>ZDB.D_QANSWER</code> table reference
     */
    public DQanswer(String alias) {
        this(DSL.name(alias), D_QANSWER);
    }

    /**
     * Create an aliased <code>ZDB.D_QANSWER</code> table reference
     */
    public DQanswer(Name alias) {
        this(alias, D_QANSWER);
    }

    /**
     * Create a <code>ZDB.D_QANSWER</code> table reference
     */
    public DQanswer() {
        this(DSL.name("D_QANSWER"), null);
    }

    public <O extends Record> DQanswer(Table<O> child, ForeignKey<O, DQanswerRecord> key) {
        super(child, key, D_QANSWER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Zdb.ZDB;
    }

    @Override
    public UniqueKey<DQanswerRecord> getPrimaryKey() {
        return Keys.KEY_D_QANSWER_PRIMARY;
    }

    @Override
    public DQanswer as(String alias) {
        return new DQanswer(DSL.name(alias), this);
    }

    @Override
    public DQanswer as(Name alias) {
        return new DQanswer(alias, this);
    }

    @Override
    public DQanswer as(Table<?> alias) {
        return new DQanswer(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DQanswer rename(String name) {
        return new DQanswer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DQanswer rename(Name name) {
        return new DQanswer(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DQanswer rename(Table<?> name) {
        return new DQanswer(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<String, String, String, String, String, Boolean, Boolean, Boolean, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function11<? super String, ? super String, ? super String, ? super String, ? super String, ? super Boolean, ? super Boolean, ? super Boolean, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function11<? super String, ? super String, ? super String, ? super String, ? super String, ? super Boolean, ? super Boolean, ? super Boolean, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
