/*
 * This file is generated by jOOQ.
 */
package cn.vertxup.jet.domain;


import cn.vertxup.jet.domain.tables.IApi;
import cn.vertxup.jet.domain.tables.IJob;
import cn.vertxup.jet.domain.tables.IService;


/**
 * Convenience access to all tables in ZDB.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ZDB.I_API</code>.
     */
    public static final IApi I_API = IApi.I_API;

    /**
     * The table <code>ZDB.I_JOB</code>.
     */
    public static final IJob I_JOB = IJob.I_JOB;

    /**
     * The table <code>ZDB.I_SERVICE</code>.
     */
    public static final IService I_SERVICE = IService.I_SERVICE;
}
