/*
 * This file is generated by jOOQ.
 */
package cn.vertxup.graphic.domain;


import cn.vertxup.graphic.domain.tables.GCluster;
import cn.vertxup.graphic.domain.tables.GEdge;
import cn.vertxup.graphic.domain.tables.GGraphic;
import cn.vertxup.graphic.domain.tables.GNode;


/**
 * Convenience access to all tables in ZDB.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ZDB.G_CLUSTER</code>.
     */
    public static final GCluster G_CLUSTER = GCluster.G_CLUSTER;

    /**
     * The table <code>ZDB.G_EDGE</code>.
     */
    public static final GEdge G_EDGE = GEdge.G_EDGE;

    /**
     * The table <code>ZDB.G_GRAPHIC</code>.
     */
    public static final GGraphic G_GRAPHIC = GGraphic.G_GRAPHIC;

    /**
     * The table <code>ZDB.G_NODE</code>.
     */
    public static final GNode G_NODE = GNode.G_NODE;
}
