/*
 * This file is generated by jOOQ.
 */
package cn.vertxup.tpl.domain;


import cn.vertxup.tpl.domain.tables.MyBag;
import cn.vertxup.tpl.domain.tables.MyDesktop;
import cn.vertxup.tpl.domain.tables.MyFavor;
import cn.vertxup.tpl.domain.tables.MyMenu;
import cn.vertxup.tpl.domain.tables.MyNotify;
import cn.vertxup.tpl.domain.tables.MySetting;
import cn.vertxup.tpl.domain.tables.MyTpl;
import cn.vertxup.tpl.domain.tables.TplMessage;
import cn.vertxup.tpl.domain.tables.TplModel;
import cn.vertxup.tpl.domain.tables.TplTicket;


/**
 * Convenience access to all tables in ZDB.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ZDB.MY_BAG</code>.
     */
    public static final MyBag MY_BAG = MyBag.MY_BAG;

    /**
     * The table <code>ZDB.MY_DESKTOP</code>.
     */
    public static final MyDesktop MY_DESKTOP = MyDesktop.MY_DESKTOP;

    /**
     * The table <code>ZDB.MY_FAVOR</code>.
     */
    public static final MyFavor MY_FAVOR = MyFavor.MY_FAVOR;

    /**
     * The table <code>ZDB.MY_MENU</code>.
     */
    public static final MyMenu MY_MENU = MyMenu.MY_MENU;

    /**
     * The table <code>ZDB.MY_NOTIFY</code>.
     */
    public static final MyNotify MY_NOTIFY = MyNotify.MY_NOTIFY;

    /**
     * The table <code>ZDB.MY_SETTING</code>.
     */
    public static final MySetting MY_SETTING = MySetting.MY_SETTING;

    /**
     * The table <code>ZDB.MY_TPL</code>.
     */
    public static final MyTpl MY_TPL = MyTpl.MY_TPL;

    /**
     * The table <code>ZDB.TPL_MESSAGE</code>.
     */
    public static final TplMessage TPL_MESSAGE = TplMessage.TPL_MESSAGE;

    /**
     * The table <code>ZDB.TPL_MODEL</code>.
     */
    public static final TplModel TPL_MODEL = TplModel.TPL_MODEL;

    /**
     * The table <code>ZDB.TPL_TICKET</code>.
     */
    public static final TplTicket TPL_TICKET = TplTicket.TPL_TICKET;
}
