/*
 * This file is generated by jOOQ.
 */
package cn.vertxup.doc.domain;


import cn.vertxup.doc.domain.tables.DComment;
import cn.vertxup.doc.domain.tables.DDoc;
import cn.vertxup.doc.domain.tables.DDocClause;
import cn.vertxup.doc.domain.tables.DDocSegment;
import cn.vertxup.doc.domain.tables.DExam;
import cn.vertxup.doc.domain.tables.DPaper;
import cn.vertxup.doc.domain.tables.DPaperRef;
import cn.vertxup.doc.domain.tables.DQanswer;
import cn.vertxup.doc.domain.tables.DQstore;
import cn.vertxup.doc.domain.tables.DQuestion;
import cn.vertxup.doc.domain.tables.DRefer;
import cn.vertxup.doc.domain.tables.DReply;
import cn.vertxup.doc.domain.tables.DReplyItem;
import cn.vertxup.doc.domain.tables.DResult;


/**
 * Convenience access to all tables in ZDB.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ZDB.D_COMMENT</code>.
     */
    public static final DComment D_COMMENT = DComment.D_COMMENT;

    /**
     * The table <code>ZDB.D_DOC</code>.
     */
    public static final DDoc D_DOC = DDoc.D_DOC;

    /**
     * The table <code>ZDB.D_DOC_CLAUSE</code>.
     */
    public static final DDocClause D_DOC_CLAUSE = DDocClause.D_DOC_CLAUSE;

    /**
     * The table <code>ZDB.D_DOC_SEGMENT</code>.
     */
    public static final DDocSegment D_DOC_SEGMENT = DDocSegment.D_DOC_SEGMENT;

    /**
     * The table <code>ZDB.D_EXAM</code>.
     */
    public static final DExam D_EXAM = DExam.D_EXAM;

    /**
     * The table <code>ZDB.D_PAPER</code>.
     */
    public static final DPaper D_PAPER = DPaper.D_PAPER;

    /**
     * The table <code>ZDB.D_PAPER_REF</code>.
     */
    public static final DPaperRef D_PAPER_REF = DPaperRef.D_PAPER_REF;

    /**
     * The table <code>ZDB.D_QANSWER</code>.
     */
    public static final DQanswer D_QANSWER = DQanswer.D_QANSWER;

    /**
     * The table <code>ZDB.D_QSTORE</code>.
     */
    public static final DQstore D_QSTORE = DQstore.D_QSTORE;

    /**
     * The table <code>ZDB.D_QUESTION</code>.
     */
    public static final DQuestion D_QUESTION = DQuestion.D_QUESTION;

    /**
     * The table <code>ZDB.D_REFER</code>.
     */
    public static final DRefer D_REFER = DRefer.D_REFER;

    /**
     * The table <code>ZDB.D_REPLY</code>.
     */
    public static final DReply D_REPLY = DReply.D_REPLY;

    /**
     * The table <code>ZDB.D_REPLY_ITEM</code>.
     */
    public static final DReplyItem D_REPLY_ITEM = DReplyItem.D_REPLY_ITEM;

    /**
     * The table <code>ZDB.D_RESULT</code>.
     */
    public static final DResult D_RESULT = DResult.D_RESULT;
}
