/*
 * This file is generated by jOOQ.
 */
package cn.vertxup.integration.domain;


import cn.vertxup.integration.domain.tables.*;
import io.vertx.mod.ke.refine.Ke;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Db extends SchemaImpl {

    /**
     * The reference instance of <code>DB_ETERNAL</code>
     */
    public static final Db DB_ETERNAL = new Db();
    private static final long serialVersionUID = 1L;
    /**
     * The table <code>DB_ETERNAL.D_COMMENT</code>.
     */
    public final DComment D_COMMENT = DComment.D_COMMENT;

    /**
     * The table <code>DB_ETERNAL.D_DOC</code>.
     */
    public final DDoc D_DOC = DDoc.D_DOC;

    /**
     * The table <code>DB_ETERNAL.D_DOC_CLAUSE</code>.
     */
    public final DDocClause D_DOC_CLAUSE = DDocClause.D_DOC_CLAUSE;

    /**
     * The table <code>DB_ETERNAL.D_DOC_SEGMENT</code>.
     */
    public final DDocSegment D_DOC_SEGMENT = DDocSegment.D_DOC_SEGMENT;

    /**
     * The table <code>DB_ETERNAL.D_REFER</code>.
     */
    public final DRefer D_REFER = DRefer.D_REFER;

    /**
     * The table <code>DB_ETERNAL.D_RESULT</code>.
     */
    public final DResult D_RESULT = DResult.D_RESULT;

    /**
     * The table <code>DB_ETERNAL.I_DIRECTORY</code>.
     */
    public final IDirectory I_DIRECTORY = IDirectory.I_DIRECTORY;

    /**
     * The table <code>DB_ETERNAL.I_INTEGRATION</code>.
     */
    public final IIntegration I_INTEGRATION = IIntegration.I_INTEGRATION;

    /**
     * The table <code>DB_ETERNAL.I_MESSAGE</code>.
     */
    public final IMessage I_MESSAGE = IMessage.I_MESSAGE;

    /**
     * The table <code>DB_ETERNAL.I_PORTFOLIO</code>.
     */
    public final IPortfolio I_PORTFOLIO = IPortfolio.I_PORTFOLIO;

    /**
     * No further instances allowed
     */
    private Db() {
        super(Ke.getDatabase(), null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            DComment.D_COMMENT,
            DDoc.D_DOC,
            DDocClause.D_DOC_CLAUSE,
            DDocSegment.D_DOC_SEGMENT,
            DRefer.D_REFER,
            DResult.D_RESULT,
            IDirectory.I_DIRECTORY,
            IIntegration.I_INTEGRATION,
            IMessage.I_MESSAGE,
            IPortfolio.I_PORTFOLIO
        );
    }
}
